# Generated by Django 6.0.7 on 2026-08-01 07:19

import django.core.validators
import django.db.models.deletion
import re
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Firm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('firm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='clients.firm')),
            ],
            options={
                'verbose_name_plural': 'categories',
            },
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pan', models.CharField(max_length=10, validators=[django.core.validators.RegexValidator(message='PAN must match the format AAAAA9999A (5 letters, 4 digits, 1 letter).', regex=re.compile('^[A-Z]{5}[0-9]{4}[A-Z]{1}$'))])),
                ('name', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=20)),
                ('aadhar_hash', models.CharField(blank=True, editable=False, max_length=64, null=True)),
                ('aadhar_masked', models.CharField(blank=True, editable=False, max_length=14, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('categories', models.ManyToManyField(related_name='clients', to='clients.category')),
                ('firm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clients', to='clients.firm')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('firm', 'pan'), name='unique_pan_per_firm')],
            },
        ),
        migrations.AddConstraint(
            model_name='category',
            constraint=models.UniqueConstraint(fields=('firm', 'name'), name='unique_category_per_firm'),
        ),
    ]
