# Generated by Django 6.0.7 on 2026-08-01 07:30

import django.contrib.postgres.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20)),
                ('display_name', models.CharField(max_length=255)),
                ('keywords', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), blank=True, default=list)),
                ('is_base', models.BooleanField(default=False)),
                ('firm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='doc_codes', to='clients.firm')),
            ],
        ),
        migrations.AddField(
            model_name='category',
            name='doc_codes',
            field=models.ManyToManyField(blank=True, related_name='categories', to='clients.doccode'),
        ),
        migrations.AddConstraint(
            model_name='doccode',
            constraint=models.UniqueConstraint(fields=('firm', 'code'), name='unique_doccode_per_firm'),
        ),
    ]
