# Generated by Django 6.0.7 on 2026-08-01 09:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0004_client_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReminderLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stage', models.CharField(choices=[('initial', 'Initial Request'), ('followup', 'Follow-up')], max_length=10)),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reminder_logs', to='clients.client')),
                ('firm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reminder_logs', to='clients.firm')),
            ],
        ),
    ]
