# Generated by Django 6.0.7 on 2026-08-01 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0005_reminderlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='reminderlog',
            name='body',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='reminderlog',
            name='subject',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
    ]
