# Generated by Django 6.0.7 on 2026-08-05 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0008_reminderlog_sent_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='account_number',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
    ]
