# Generated by Django 6.0.7 on 2026-08-01 08:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0003_userprofile'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Batch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ay', models.CharField(max_length=10)),
                ('folder_path', models.CharField(max_length=1000)),
                ('files_found', models.IntegerField(default=0)),
                ('files_filed', models.IntegerField(default=0)),
                ('files_review', models.IntegerField(default=0)),
                ('files_skipped', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('firm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='batches', to='clients.firm')),
                ('triggered_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ay', models.CharField(max_length=10)),
                ('original_filename', models.CharField(max_length=500)),
                ('content_hash', models.CharField(db_index=True, max_length=64)),
                ('extraction_method', models.CharField(choices=[('text', 'Text'), ('ocr', 'OCR'), ('none', 'None')], default='none', max_length=10)),
                ('detected_pan', models.CharField(blank=True, max_length=10, null=True)),
                ('detected_aadhar_masked', models.CharField(blank=True, max_length=14, null=True)),
                ('detected_phone', models.CharField(blank=True, max_length=20, null=True)),
                ('match_method', models.CharField(choices=[('pan', 'PAN'), ('aadhar', 'Aadhar'), ('phone', 'Phone'), ('none', 'No match')], default='none', max_length=10)),
                ('status', models.CharField(choices=[('review', 'Needs Review'), ('filed', 'Filed')], default='review', max_length=10)),
                ('review_reason', models.CharField(blank=True, max_length=500, null=True)),
                ('storage_path', models.CharField(max_length=1000)),
                ('archive_path', models.CharField(blank=True, max_length=1000, null=True)),
                ('is_possible_duplicate', models.BooleanField(default=False)),
                ('filed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='documents.batch')),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documents', to='clients.client')),
                ('doc_code', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documents', to='clients.doccode')),
                ('duplicate_of', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='duplicates', to='documents.document')),
                ('firm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='clients.firm')),
            ],
        ),
    ]
