# Generated by Django 6.0.7 on 2026-08-05 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0002_alter_batch_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='detected_account',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='document',
            name='match_method',
            field=models.CharField(choices=[('pan', 'PAN'), ('aadhar', 'Aadhar'), ('account', 'Account Number'), ('phone', 'Phone'), ('none', 'No match')], default='none', max_length=10),
        ),
    ]
